### PR TITLE
Homework1

### PR DESCRIPTION
**Pull request by baranovdev**

### CODE REVIEW

**Review by OcheretnyArtem — APPROVED** [review]
Great job!

**Review by Gizcerbes — APPROVED** [review]

**Review by YarikGuk — APPROVED** [review]

**Review by Berikz80 — APPROVED** [review]
Good work

**Review by artemVash — APPROVED** [review]
👍

**Review by Gizcerbes — COMMENTED** [review]
java.lang.IllegalArgumentException: Path must not be empty.
        at com.squareup.picasso.Picasso.load(Picasso.java:332)
        at by.baranovdev.homework.ImageLoaderActivity$onCreate$1.onClick(ImageLoaderActivity.kt:24)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Review by e-kleban — APPROVED** [review]

**Review by TMSlebedev — APPROVED** [review]

**Pull request merged**
